class ErrorCodes:
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_QUERY = "INVALID_QUERY"
    INVALID_EXTERNAL_ID = "INVALID_EXTERNAL_ID"
    MOVIE_NOT_FOUND = "MOVIE_NOT_FOUND"
    TMDB_NOT_CONFIGURED = "TMDB_NOT_CONFIGURED"
    PROVIDER_UNAUTHORIZED = "PROVIDER_UNAUTHORIZED"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    REDIS_UNAVAILABLE = "REDIS_UNAVAILABLE"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class CacheHeaders:
    STATUS = "X-Cache"
    HIT = "HIT"
    MISS = "MISS"
    FALLBACK = "FALLBACK"
